# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da00355cf87bac2b7bb2c6b60d74164f6c4d557839b6181ea77e96d17ae6030352bab981e53ad16e34db990533ebe92022b86d8653cacac83fd57ea7ca45c0c

test:
  secret_key_base: 81b6014262c9681cd7bbefc3a7743a08c0c3ff3b79a1890dcc51dd644c4c87d2dbbea6316aa542ce3e64143530a7e0fa33b2272c4dd69b20b8812d770cbbbb80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
